# Generated by Django 3.1.3 on 2020-11-25 18:19

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='year')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='authors')),
                ('born', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='born', to='api.year')),
                ('died', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='died', to='api.year')),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date created')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='works')),
                ('body', models.TextField(verbose_name='body')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('authors', models.ManyToManyField(blank=True, null=True, to='api.Author')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='api.city')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='api.type')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='api.year')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
