# Generated by Django 3.1.3 on 2020-11-13 18:56

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='author_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='works'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='authors'),
        ),
    ]
