# Generated by Django 3.1.3 on 2020-11-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201122_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='author_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='api.author'),
            preserve_default=False,
        ),
    ]
