# Generated by Django 3.1.3 on 2020-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_art_author_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='authors', to='api.Author'),
        ),
    ]
