# Generated by Django 3.1.3 on 2020-11-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_art_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['year']},
        ),
        migrations.RemoveField(
            model_name='art',
            name='authors',
        ),
    ]
