# Generated by Django 3.1.3 on 2020-11-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201125_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='art',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year created'),
        ),
    ]
